[package]
name = "hello-world"
version = "0.1.0"
authors = ["Zhishi <whfuyn@outlook.com>"]
edition = "2018"


[dependencies]

[target.'cfg(any(target_env = "", target_env = "gnu", target_env = "msvc"))'.dependencies]
jemallocator-global = "0.3.2"
