name: release
on:
  push:
    tags:
      - 'v[0-9]+.*'
jobs:
  publish-release:
    name: Publish Release
    env:
      BINARY_NAME: hello-world
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, linux-musl, win-msvc, macos, macos-arm]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: linux-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - build: win-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: macos
            os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          components: rustfmt, clippy

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          # use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
            if [ "${{ matrix.build }}" == "win-msvc" ]; then
              zip -j ${{ env.BINARY_NAME }}-${{ matrix.target }}.zip target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}
            else
              tar czf ${{ env.BINARY_NAME }}-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release ${{ env.BINARY_NAME }}
      
      - name: Upload release archive
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.BINARY_NAME }}-${{ matrix.target }}.zip
            ${{ env.BINARY_NAME }}-${{ matrix.target }}.tar.gz
